trigger:
- master
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo apt-get -y install bison flex
  displayName: 'Install bison and flex'

- script: gradle --init-script gradle/support/fetchDependencies.gradle init
  displayName: 'Init flat directory-style repository'

- script: gradle wrapper
  displayName: 'Create wrapper task'

- task: Gradle@2
  displayName: 'gradlew buildGhidra'
  inputs:
    #gradleWrapperFile: 'gradlew'
    workingDirectory: ''
    tasks: buildGhidra
    jdkVersionOption: 1.11