trigger:
- master
- dev

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  DISPLAY: :99.0

jobs:
  - job: Build
    timeoutInMinutes: 240
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-latest'
        mac:
          imageName: 'macOS-10.14'
    pool:
      vmImage: $(imageName)

    steps:
    - script: sudo apt-get -y install bison flex
      displayName: 'Install bison and flex (Linux)'
      condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

    - task: CacheBeta@0
      displayName: Gradle build cache
      inputs:
        key: '$(Agent.OS)-gradle-home'
        path: $(GRADLE_USER_HOME)

    - script: brew install bison flex && brew link bison --force && brew link flex --force
      displayName: 'Install bison and flex (Mac)'
      condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))

    - script: gradle --init-script gradle/support/fetchDependencies.gradle init
      displayName: 'Init flat directory-style repository'

    - script: gradle wrapper
      displayName: 'Create wrapper task'

    - script: (/usr/bin/Xvfb :99 -screen 0 1280x1024x24 &)
      displayName: "Start Xvfb for DISPLAY=$(DISPLAY)"
      condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

    - task: Gradle@2
      displayName: 'gradlew buildGhidra'
      inputs:
        workingDirectory: ''
        options: '--build-cache'
        tasks: buildGhidra
        jdkVersionOption: 1.11

    - task: Gradle@2
      displayName: 'gradlew unitTestReport'
      inputs:
        workingDirectory: ''
        options: '--build-cache'
        tasks: unitTestReport
        jdkVersionOption: 1.11

    - task: Gradle@2
      displayName: 'gradlew integrationTest'
      inputs:
        workingDirectory: ''
        options: '--build-cache'
        tasks: integrationTest
        jdkVersionOption: 1.11
      condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false), notIn(variables['Build.Reason'], 'PullRequest', 'CheckInShelveset'))

    - task: Gradle@2
      displayName: 'gradlew --stop'
      inputs:
        workingDirectory: ''
        options: '--stop'
        jdkVersionOption: 1.11

    - task: CopyFiles@2
      inputs:
        sourceFolder: 'build/dist'
        targetFolder: '$(build.artifactstagingdirectory)'
      condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false), notIn(variables['Build.Reason'], 'PullRequest', 'CheckInShelveset'))

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        artifactName: artifacts
        artifactType: Container
      condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false), notIn(variables['Build.Reason'], 'PullRequest', 'CheckInShelveset'))
