schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - master
jobs:
  - job: Instructure
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          git remote add upstream https://github.com/NationalSecurityAgency/ghidra
          git fetch upstream
          git checkout master
          git merge upstream/master --ff-only
          git push
        displayName: 'Update master from upstream'
