schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - master
jobs:
  - job: Instructure
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          git remote -v
          git remote add upstream https://github.com/NationalSecurityAgency/ghidra
          git fetch upstream master
          git checkout origin/master
          git merge upstream/master --ff-only
          git push origin master
        displayName: 'Update master from upstream'
